### ISSUE TITLE
MySQL Index Length Too Long

### ISSUE THREAD

**Issue by dwriconeapi** [Access4Learning/sif3-framework-java#44]
I was updating my implementation of the framework from version 0.12.0 to 0.13.0 using the script found [here](https://github.com/Access4Learning/sif3-framework-java/blob/master/SIF3InfraREST/DB/DDL/Datafix/current/v0.12.0-v0.13.0/Datafix_Job_mysql.sql). However, MySQL reported the following error:

`0 | 6 | 09:47:15 | CREATE INDEX JOB_FINGERPRT_ADPTYPE_IDX ON SIF3_JOB (FINGERPRINT ASC, SERVICE_NAME ASC, ADAPTER_TYPE ASC) | Error Code: 1071. Specified key was too long; max key length is 767 bytes | 0.000 sec
-- | -- | -- | -- | -- | --`

I would assume that this applies to many other indexes in the statement, but I have yet to try those yet.

Also, according to the MySQL [documentation ](https://dev.mysql.com/doc/refman/5.6/en/identifiers.html)the max length for an index name is 64 characters. However, none of these names are over 64 characters, so I think it has something to do with the encoding type, which is utf8.

**Comment by joerghuber** [comment]
Hi Dan,
The issue is not the length of the index name but probably the total length of the columns. over which the index is generated. I remember having a similar issue with the "SECURITY_TOKEN' index on the SIF3_SESSION table. See also https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes.
You will notice that the limits are higher with newer versions of MySQL. So depending which version you use you may run into this issue. My DB is a newer version now, so I did not run into the issue. with the SIF3_JOB
What I did to get around the issue with the SIF3_SESSION table is to use a smaller column length then create the index and finally altered the columns back to the original length. Try this and it should work. You may need to do a similar thing with the SIF3_JOB_EVENT table.

Cheers Joerg

**Comment by dwriconeapi** [comment]
Hi Joerg,
Thanks for the help. I'll give this a try tomorrow. 👍
